# Generated by Django 6.0.1 on 2026-01-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_book', 'Can view book'), ('can_create_book', 'Can create book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
